### ISSUE TITLE
problem with my own small dataset : ValueError: negative step not yet supported

### ISSUE THREAD

**Issue by ohadianoush** [chaiyujin/dctts-pytorch#7]
hi, i create my own dataset in Persian language with 229 rows ( i know its very few but its only for test ) . 
at first i change this : (    vocab = "PE ابپتثجچ‌حخدذرز‌ژس‌شصضطظعغفقکگلمنوهیءآاًهٔة'.?")
and after runing (python3 main.py --action train --module Text2Mel) i get this error:

ule Text2Mel
train: Text to Mel
loop 0
▝[1/8] |gs: 0, mels: 0.321015, bd1: 0.693171, atten: 0.637633, scale: 99.999000| [0.0% eta ETA unknown]Traceback (most recent call last):
  File "main.py", line 62, in <module>
    main()
  File "main.py", line 47, in main
    train(args.module, args.load)
  File "/home/ai/dctts-pytorch/pkg/train.py", line 54, in train
    train_text2mel(load_trained)
  File "/home/ai/dctts-pytorch/pkg/train.py", line 197, in train_text2mel
    plot_spectrum(mels[0].cpu().data, "mel_true", gs, dir=logdir)
  File "/home/ai/dctts-pytorch/pkg/utils.py", line 110, in plot_spectrum
    im = ax.imshow(np.flip(spectrum, 0), cmap="jet", aspect=0.2 * spectrum.shape[1] / spectrum.shape[0])
  File "<__array_function__ internals>", line 6, in flip
  File "/home/ai/Downloads/con/lib/python3.7/site-packages/numpy/lib/function_base.py", line 254, in flip
    return m[indexer]
ValueError: negative step not yet supported

**Comment by kwmkwm** [comment]
I had the same error with the un-altered code.  I downgraded PyTorch to 1.0.0 that solved the problem.
